In [1]:
print("=" * 50)
print("       MOVIE RECOMMENDATION SYSTEM")
print("=" * 50)
print("Project Type: Artificial Intelligence / Machine Learning")
print("Recommendation Method: Content-Based Filtering")
print("Technologies: Python, Pandas, Scikit-learn, Gradio")
print("=" * 50)
print("Welcome to the Movie Recommendation Project!")

==================================================
       MOVIE RECOMMENDATION SYSTEM
==================================================
Project Type: Artificial Intelligence / Machine Learning
Recommendation Method: Content-Based Filtering
Technologies: Python, Pandas, Scikit-learn, Gradio
==================================================
Welcome to the Movie Recommendation Project!

In [3]:
import pandas as pd

movies = {
    'Movie_Title': [
            'Harry Potter',
                    'Fantastic Beasts',
                            'The Chronicles of Narnia',
                                    'The Lord of the Rings',
                                            'Avengers: Endgame',
                                                    'Iron Man',
                                                            'Spider-Man',
                                                                    'The Dark Knight',
                                                                            'Interstellar',
                                                                                    'Inception',
                                                                                            'Titanic',
                                                                                                    'The Notebook',
                                                                                                            'Jurassic Park',
                                                                                                                    'Avatar',
                                                                                                                            'The Lion King'
                                                                                                                                ],

                                                                                                                                    'Genre': [
                                                                                                                                            'Fantasy Adventure Magic',
                                                                                                                                                    'Fantasy Adventure Magic',
                                                                                                                                                            'Fantasy Adventure Magic',
                                                                                                                                                                    'Fantasy Adventure Magic',
                                                                                                                                                                            'Action Superhero Adventure',
                                                                                                                                                                                    'Action Superhero Science Fiction',
                                                                                                                                                                                            'Action Superhero Adventure',
                                                                                                                                                                                                    'Action Crime Thriller',
                                                                                                                                                                                                            'Science Fiction Space Adventure',
                                                                                                                                                                                                                    'Science Fiction Thriller',
                                                                                                                                                                                                                            'Romance Drama',
                                                                                                                                                                                                                                    'Romance Drama',
                                                                                                                                                                                                                                            'Science Fiction Adventure',
                                                                                                                                                                                                                                                    'Science Fiction Fantasy Adventure',
                                                                                                                                                                                                                                                            'Animation Family Adventure'
                                                                                                                                                                                                                                                                ],

                                                                                                                                                                                                                                                                    'Description': [
                                                                                                                                                                                                                                                                            'A young wizard learns magic and fights dark forces.',
                                                                                                                                                                                                                                                                                    'A wizard explores a magical world filled with fantastic creatures.',
                                                                                                                                                                                                                                                                                            'Children enter a magical kingdom and experience an epic adventure.',
                                                                                                                                                                                                                                                                                                    'Heroes embark on a dangerous journey to destroy a powerful ring.',
                                                                                                                                                                                                                                                                                                            'Superheroes unite to save the universe from a powerful enemy.',
                                                                                                                                                                                                                                                                                                                    'A genius inventor builds an advanced suit to fight evil.',
                                                                                                                                                                                                                                                                                                                            'A young superhero protects his city from dangerous villains.',
                                                                                                                                                                                                                                                                                                                                    'A masked hero fights crime and protects Gotham City.',
                                                                                                                                                                                                                                                                                                                                            'Astronauts travel through space to find a new home for humanity.',
                                                                                                                                                                                                                                                                                                                                                    'A skilled thief enters dreams to complete a dangerous mission.',
                                                                                                                                                                                                                                                                                                                                                            'Two people fall in love aboard a famous ocean liner.',
                                                                                                                                                                                                                                                                                                                                                                    'Two people experience a deep and lasting romantic relationship.',
                                                                                                                                                                                                                                                                                                                                                                            'Scientists encounter dinosaurs in a dangerous theme park.',
                                                                                                                                                                                                                                                                                                                                                                                    'A human explorer discovers an alien world and its inhabitants.',
                                                                                                                                                                                                                                                                                                                                                                                            'A young lion learns about courage, family, and responsibility.'
                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                                }

df = pd.DataFrame(movies)

print("MOVIE DATASET CREATED SUCCESSFULLY!")
print("Total Movies:", len(df))
display(df)

MOVIE DATASET CREATED SUCCESSFULLY!
Total Movies: 15

,Movie_Title,Genre,Description
0,Harry Potter,Fantasy Adventure Magic,A young wizard learns magic and fights dark fo...
1,Fantastic Beasts,Fantasy Adventure Magic,A wizard explores a magical world filled with ...
2,The Chronicles of Narnia,Fantasy Adventure Magic,Children enter a magical kingdom and experienc...
3,The Lord of the Rings,Fantasy Adventure Magic,Heroes embark on a dangerous journey to destro...
4,Avengers: Endgame,Action Superhero Adventure,Superheroes unite to save the universe from a ...
5,Iron Man,Action Superhero Science Fiction,A genius inventor builds an advanced suit to f...
6,Spider-Man,Action Superhero Adventure,A young superhero protects his city from dange...
7,The Dark Knight,Action Crime Thriller,A masked hero fights crime and protects Gotham...
8,Interstellar,Science Fiction Space Adventure,Astronauts travel through space to find a new ...
9,Inception,Science Fiction Thriller,A skilled thief enters dreams to complete a da...
10,Titanic,Romance Drama,Two people fall in love aboard a famous ocean ...
11,The Notebook,Romance Drama,Two people experience a deep and lasting roman...
12,Jurassic Park,Science Fiction Adventure,Scientists encounter dinosaurs in a dangerous ...
13,Avatar,Science Fiction Fantasy Adventure,A human explorer discovers an alien world and ...
14,The Lion King,Animation Family Adventure,"A young lion learns about courage, family, and..."

In [4]:
df['Features'] = df['Genre'] + ' ' + df['Description']

print("MOVIE FEATURES CREATED SUCCESSFULLY!")
display(df[['Movie_Title', 'Features']])

MOVIE FEATURES CREATED SUCCESSFULLY!

,Movie_Title,Features
0,Harry Potter,Fantasy Adventure Magic A young wizard learns ...
1,Fantastic Beasts,Fantasy Adventure Magic A wizard explores a ma...
2,The Chronicles of Narnia,Fantasy Adventure Magic Children enter a magic...
3,The Lord of the Rings,Fantasy Adventure Magic Heroes embark on a dan...
4,Avengers: Endgame,Action Superhero Adventure Superheroes unite t...
5,Iron Man,Action Superhero Science Fiction A genius inve...
6,Spider-Man,Action Superhero Adventure A young superhero p...
7,The Dark Knight,Action Crime Thriller A masked hero fights cri...
8,Interstellar,Science Fiction Space Adventure Astronauts tra...
9,Inception,Science Fiction Thriller A skilled thief enter...
10,Titanic,Romance Drama Two people fall in love aboard a...
11,The Notebook,Romance Drama Two people experience a deep and...
12,Jurassic Park,Science Fiction Adventure Scientists encounter...
13,Avatar,Science Fiction Fantasy Adventure A human expl...
14,The Lion King,Animation Family Adventure A young lion learns...

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['Features'])

print("TF-IDF conversion completed successfully!")
print("Number of movies:", tfidf_matrix.shape[0])
print("Number of features:", tfidf_matrix.shape[1])

TF-IDF conversion completed successfully!
Number of movies: 15
Number of features: 91

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tfidf_matrix)

print("Movie similarity calculated successfully!")
print("Similarity matrix shape:", similarity_matrix.shape)

Movie similarity calculated successfully!
Similarity matrix shape: (15, 15)

In [11]:
movie_title = 'Harry Potter'

movie_index = df[df['Movie_Title'] == movie_title].index[0]

scores = list(enumerate(similarity_matrix[movie_index]))
scores = sorted(scores, key=lambda x: x[1], reverse=True)

for index, score in scores[1:6]:
    print(df.iloc[index]['Movie_Title'], "-", df.iloc[index]['Genre'])

Fantastic Beasts - Fantasy Adventure Magic
The Chronicles of Narnia - Fantasy Adventure Magic
The Lord of the Rings - Fantasy Adventure Magic
The Lion King - Animation Family Adventure
Spider-Man - Action Superhero Adventure

In [14]:
import gradio as gr

def get_movies(movie_title):
    movie_index = df[df['Movie_Title'] == movie_title].index[0]
scores = list(enumerate(similarity_matrix[movie_index]))
scores = sorted(scores, key=lambda x: x[1], reverse=True)
result = [df.iloc[i]['Movie_Title'] for i, score in scores[1:6]]
print("\n".join(result))

app = gr.Interface(
                        fn=lambda movie_title: "\n".join(
                                [df.iloc[i]['Movie_Title'] for i, score in
                                         sorted(enumerate(similarity_matrix[
                                                      df[df['Movie_Title'] == movie_title].index[0]
                                                               ]), key=lambda x: x[1], reverse=True)[1:6]]
                                                                   ),
                                                                       inputs=gr.Dropdown(
                                                                               choices=df['Movie_Title'].tolist(),
                                                                                       label="Select a Movie"
                                                                                           ),
                                                                                               outputs=gr.Textbox(label="Recommended Movies"),
                                                                                                   title="Movie Recommendation System",
                                                                                                       description="Select a movie to discover five similar movies!"
                                                                                                       )

app.launch(share=True)

Fantastic Beasts
The Chronicles of Narnia
The Lord of the Rings
The Lion King
Spider-Man
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://4723470e1da0d2b18b.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)